spring.application.name=passkey-demo

# Server Port
server.port=8082

# MySQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/passkey_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dung@1305
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# JWT Secret (thay đổi cho production)
jwt.secret=yourSecretKeyHereAtLeast32CharactersLongForSecurity
# 1 day in milliseconds
jwt.expiration=86400000

# WebAuthn Configuration
webauthn.rp.id=nonevadingly-nonconversant-amber.ngrok-free.dev
webauthn.rp.name=Passkey Demo
webauthn.origin=https://nonevadingly-nonconversant-amber.ngrok-free.dev